# Generated by Django 3.2.6 on 2022-05-29 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name="Имя tag'а")),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.CharField(blank=True, max_length=511, verbose_name='Краткая информация об авторе')),
                ('author', models.BooleanField(default=False, verbose_name='Автор')),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(default='avatars/default-avatar.jpg', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=511, verbose_name='Описание поста')),
                ('image_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='pictures/')),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Содержание')),
                ('description_for_search_engines', models.CharField(blank=True, max_length=511)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.profile', verbose_name='Автор')),
                ('tags', models.ManyToManyField(to='post.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('is_published', '-pub_date'),
            },
        ),
    ]
